// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ56wq3miVgQ41c24AluQivOAvPJr1Ixw',
    appId: '1:400047291477:web:472f54236f41b47b5028dc',
    messagingSenderId: '400047291477',
    projectId: 'emart-606a9',
    authDomain: 'emart-606a9.firebaseapp.com',
    storageBucket: 'emart-606a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4adMNNXWwXZVtE5H6dN1FFZGCTD0rl-I',
    appId: '1:400047291477:android:9810a6c4ee922bab5028dc',
    messagingSenderId: '400047291477',
    projectId: 'emart-606a9',
    storageBucket: 'emart-606a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Tdi06E0WbnwHyYbW0K9FWvv6B7NX3yw',
    appId: '1:400047291477:ios:545361fc55ab70895028dc',
    messagingSenderId: '400047291477',
    projectId: 'emart-606a9',
    storageBucket: 'emart-606a9.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Tdi06E0WbnwHyYbW0K9FWvv6B7NX3yw',
    appId: '1:400047291477:ios:545361fc55ab70895028dc',
    messagingSenderId: '400047291477',
    projectId: 'emart-606a9',
    storageBucket: 'emart-606a9.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ56wq3miVgQ41c24AluQivOAvPJr1Ixw',
    appId: '1:400047291477:web:4c38447474ce7fd35028dc',
    messagingSenderId: '400047291477',
    projectId: 'emart-606a9',
    authDomain: 'emart-606a9.firebaseapp.com',
    storageBucket: 'emart-606a9.appspot.com',
  );
}
